version: "3.8"

services:
  adminer:
    restart: always
    image: adminer:latest
    ports:
      - ${ADMINER_PORT}:8080

  postgres:
    restart: always
    image: postgres:14.5
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres_demo_db:/var/lib/postgresql/data

  backend:
    restart: always
    build:
      context: ./apps/backend/
      dockerfile: ./Dockerfile
    ports:
      - ${BACKEND_PORT}:8080
    depends_on:
      - postgres
    environment:
      ConnectionStrings__DATABASE_URL: "Host=postgres;Database=${POSTGRES_DB};Username=${POSTGRES_USER};Password=${POSTGRES_PASSWORD}"

  frontend:
    restart: always
    build:
      context: ./
      dockerfile: ./apps/frontend/Dockerfile
      args:
        VITE_API_URL: ${VITE_API_URL}
    ports:
      - ${FRONTEND_PORT}:8080
    depends_on:
      - backend

volumes:
  postgres_demo_db:
