version: "3.8"

services:
  postgres:
    restart: always
    image: postgres:14.5
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    networks:
      - db
      - task
    volumes:
      - postgres_prod_db:/var/lib/postgresql/data

  backend:
    restart: always
    image: registry.main.lwjerri.dev/lwjerri/csharpboard-backend:latest
    environment:
      ConnectionStrings__DATABASE_URL: "Host=postgres;Database=${POSTGRES_DB};Username=${POSTGRES_USER};Password=${POSTGRES_PASSWORD}"
    networks:
      - task
      - caddy
    depends_on:
      - postgres
    labels:
      caddy: https://api.csharpboard.main.lwjerri.dev
      caddy.reverse_proxy: "{{upstreams 8080}}"

  frontend:
    restart: always
    image: registry.main.lwjerri.dev/lwjerri/csharpboard-frontend:latest
    environment:
      - VITE_API_URL=${VITE_API_URL}
    networks:
      - caddy
    depends_on:
      - backend
    labels:
      caddy: https://csharpboard.main.lwjerri.dev
      caddy.reverse_proxy: "{{upstreams 8080}}"

networks:
  caddy:
    external: true
  db:
    external: true
  task:

volumes:
  postgres_prod_db:
